#! /usr/bin/env python

import getpass
import sys
import telnetlib

# Connection engine - utilizes an inventory file
# This file is a list of IP addresses
# Each line is a single IP address

inventory = open("inventory.txt")

??clinic = raw_input("Enter the PCC#: ")    <Want this to be the first input to call on an individule clinic
user = raw_input("Enter your telnet username: ")
password = getpass.getpass()

##Need to figure out how to get it to "find" the PCC in inventory when called on.

# File(s) to search from, just a string
#configFile =  ???

#print('Enter search string:') ???
#searchString = clinic [Lets say this works and it finds the clinic by PCC, how do I get it to see and use the IP to connect?]



for host in inventory:
    host = host.strip()
    tn = telnetlib.Telnet(host)

    tn.read_until("Username: ")
    tn.write(user + "\n")
    if password:
        tn.read_until("Password: ")
        tn.write(password + "\n")

    # Begin ClinicTS process    
    # Setup term length         
    tn.write("term len 0\n")    

    # Take config and deposit to file
    tn.write("sh bgp sum\n")
	tn.write("sh ip int bri\n")
	tn.write("sh cdp nei\n")
	tn.write("sh ping 8.8.8.8 rep 200\n")

    # Reset terminal length
    tn.write("term len 24\n")   
    tn.write("exit\n")          

    # Write output to text file     <How do I get it to name the file "PCC# - Date"?
    config = tn.read_all()
    clinicFile = open(host + ".txt", "w")
    clinicFile.write(config)

    # Graceful closure of log file
    clinicFile.close()

# Graceful closure of inventory file
inventory.close()
